# Generated by Django 6.0.1 on 2026-03-06 11:09

from typing import Any
from django.db import migrations

def create_groups(apps: Any, schema_editor: Any) -> None:
    Group = apps.get_model("auth", "Group")

    group_names = [
        "Admin",
        "Student",
        "Teacher",
        "Wali Kelas",
    ]

    for name in group_names:
        Group.objects.get_or_create(name=name)

def remove_groups(apps: Any, schema_editor: Any):
    Group = apps.get_model("auth", "Group")

    group_names = [
        "Admin",
        "Student",
        "Teacher",
        "Wali Kelas",
    ]

    Group.objects.filter(name__in=group_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]

